### ISSUE TITLE
Titlepage with more than one-line sentences

### ISSUE THREAD

**Issue by lanadaquenada** [pvanberg/flux-beamer#1]
Right now, when setting a long phrase in the title page (in any of the `\title{}`, `\subtitle{}`,  `\author{}` or  `\institution{}`) the line does not break and hence it doesn't show up entirely. Is there a way to fix this?

Thanks for the help and also thanks for making this template, I think it's one of the cleanest out there.

**Comment by povanberg** [comment]
Hi,

The easiest way to overcome this issue is to manually insert line breaks. 

`\title{My very long title \\ My second line}`

 However line breaks may reset the style, you therefore need to reinforce it:

`\title{My very long title \\ \usebeamerfont{title}\color{primary} My second line}`
or
`\author{John Doe\\ \usebeamerfont{author}\color{Gray} Jane Doe}`

Thank you for the suggestion. I will try integrate it natively for the next update.

Have a nice day.
